name: travel_outfit_planne
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Database
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Navigation
  auto_route: ^8.1.4
  
  # Storage
  shared_preferences: ^2.3.2
  
  # State management
  provider: ^6.1.2
  
  # Image handling
  image_picker: ^1.1.2
  
  # Weather API
  http: ^1.2.2
  google_fonts: ^6.3.2
  in_app_review: ^2.0.11
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code generation
  drift_dev: ^2.20.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.13

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icons.png

flutter_launcher_icons:
  ios: true
  image_path: "assets/icons.png"
  remove_alpha_ios: true